before_script:
  - docker info

build_image:
  image: $CI_REGISTRY/group/project/docker:19.03.1
  services:
    - name: $CI_REGISTRY/group/project/docker:19.03.1-dind
      alias: docker
  only:
    - tags
  except:
    - branches
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t tuchfarber/veto-it:0.1 .
    - docker push tuchfarber/veto-it:0.1
