before_script:
  - docker info

.build_template: &build-template
  image: docker:19.03.1
  stage: build
  services:
    - docker:19.03.1-dind
  only:
    - tags
  except:
    - branches
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/tuchfarber/veto-it/$IMAGE_NAME:$CI_COMMIT_TAG -f $DOCKER_FILE .
    - docker push $CI_REGISTRY/tuchfarber/veto-it/$IMAGE_NAME:$CI_COMMIT_TAG

build_server:
  <<: *build-template
  variables:
    IMAGE_NAME: "vetoit-server"
    DOCKER_FILE: "Dockerfile-server"

build_client:
  <<: *build-template
  variables:
    IMAGE_NAME: "vetoit-client"
    DOCKER_FILE: "Dockerfile-client"
