before_script:
  - docker info

.build_template: &build-template
  image: docker:19.03.1
  stage: build
  services:
    - docker:19.03.1-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    REPO_NAME: "tuchfarber/veto-it"
    IMAGE_NAME: ""
    IMAGE_TAG: ""
    DOCKER_FILE: ""

  only:
    - tags
  except:
    - branches
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$REPO_NAME/$IMAGE_NAME:$IMAGE_TAG -f $DOCKER_FILE .
    - docker push $CI_REGISTRY/$REPO_NAME/$IMAGE_NAME:$IMAGE_TAG

build_server:
  <<: *build-template
  variables:
    IMAGE_NAME: "vetoit-server"
    IMAGE_TAG: "0.1"
    DOCKER_FILE: "Dockerfile-server"

build_client:
  <<: *build-template
  variables:
    IMAGE_NAME: "vetoit-client"
    IMAGE_TAG: "0.1"
    DOCKER_FILE: "Dockerfile-client"